### ISSUE TITLE
 SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by rogerbl** [braibaud/airthings-api#3]
Hi!
I get this error msg:  SyntaxError: 'await' outside function
when I try to run the code.
What to do with it?

**Comment by braibaud** [comment]
Are you running the code in Jupyter? If not you probably need to wrap the code in a `asyncio.run(...)` call.

**Comment by rogerbl** [comment]
I’m running it in python 3.8

Fra: Benjamin RAIBAUD ***@***.***>
Sendt: onsdag 21. april 2021 16.35
Til: braibaud/airthings-api ***@***.***>
Kopi: rogerbl ***@***.***>; Author ***@***.***>
Emne: Re: [braibaud/airthings-api] SyntaxError: 'await' outside function (#3)


Are you running the code in Jupyter? If not you probably need to wrap the code in a asyncio.run(...) call.

**Comment by braibaud** [comment]
The sample code in the README.md file is meant to run in a jupyter notebook cell for IPython > 7 which support direct invocation of async methods. Otherwise please wrap the method call in the `async.run(...)` call, as mentioned earlier.
This could help: https://blog.jupyter.org/ipython-7-0-async-repl-a35ce050f7f7

**Comment by braibaud** [comment]
FYI, I have updated the README.md to reflect what I was mentioning earlier. I am closing the issue then.
